services:
  postgres:
    image: postgres:14-alpine        
    container_name: orders_postgres  
    environment:
      POSTGRES_USER: myuser          
      POSTGRES_PASSWORD: mypassword    
      POSTGRES_DB: orders_db         
    ports:
      - "5432:5432"                  
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: